frontend:codestyle:
  stage: codestyle
  image: $CI_REGISTRY_IMAGE/dev-job-runner:$CI_PIPELINE_ID
  script:
    - cd frontend
    - npx prettier --check "src/**/*"

frontend:gitleaks:
  extends: .security:gitleaks:template
  variables:
    MODULE_PATH: "frontend/src"
